
FROM arm64v8/nginx:1.25.3

VOLUME /var/cache/nginx

## Copy our default nginx config
COPY nginx/default.conf /etc/nginx/conf.d/


RUN rm -rf /usr/share/nginx/html/*

COPY  dist/todo-angular/browser /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]
