version: '2'


networks:
  proxy:
    external: true

services:

  todo-angular:
    image: uportal/todo-angular:latest
    labels:
      - "traefik.backend=todo-angular"
      - "traefik.frontend.rule=Host:todo-angular.united-portal.com"
      - "traefik.docker.network=proxy"
      - "traefik.port=80"
      - "traefik.enable=true"

    restart: always
    ports:
      - 4000:80
    networks:
      - proxy
    environment:
      API_BASE_PATH: https://todo-h2.united-portal.com
